import type { SxProps, Theme } from '@mui/material';

export const adminStyles = {
  root: { width: '100%' },
  headerOffset: { pt: 0.5 },
  settingsGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
    gap: 3,
  },
  card: {
    p: 2.5,
    borderRadius: '12px',
    border: '1px solid var(--app-border-soft)',
    backgroundColor: 'var(--app-surface)',
    boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.06)',
  },
  compactCard: { p: 2.5, borderRadius: '12px', border: '1px solid var(--app-border-soft)' },
  cardHeader: { mb: 2.5, display: 'flex', alignItems: 'center', gap: 1.5 },
  cardIcon: { color: '#2e8b8a', fontSize: 24 },
  profileIcon: { color: '#2e8b8a', fontSize: 20 },
  cardTitle: { fontSize: '15px', fontWeight: 700, color: 'var(--app-text)' },
  cardDescription: { fontSize: '12px', color: 'var(--app-text-soft)', fontWeight: 500 },
  fieldLabel: { fontSize: '13px', color: '#647b99', fontWeight: 500, mb: 0.75 },
  textField: { '& .MuiOutlinedInput-root': { borderRadius: '8px' } },
  profileRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    pb: 1.5,
    borderBottom: '1px solid var(--app-border-soft)',
    '&:last-child': { borderBottom: 'none', pb: 0 },
  },
  profileName: { fontSize: '14px', fontWeight: 500, color: 'var(--app-text)', flex: 1 },
  smallSelect: {
    minWidth: 100,
    backgroundColor: 'var(--app-surface-soft)',
    borderRadius: '6px',
    '& .MuiOutlinedInput-notchedOutline': { borderColor: 'var(--app-border)' },
  },
  fullSelect: { borderRadius: '8px', backgroundColor: 'var(--app-surface)' },
  checkbox: { color: '#2e8b8a', '&.Mui-checked': { color: '#2e8b8a' } },
  checkboxLabel: { fontSize: '13px', color: '#647b99', fontWeight: 500 },
  saveButton: {
    backgroundColor: '#2e8b8a',
    color: '#ffffff',
    fontWeight: 700,
    fontSize: '14px',
    py: 1.5,
    px: 3,
    borderRadius: '8px',
    textTransform: 'none',
    '&:hover': { backgroundColor: '#1a5453' },
  },
  lowerGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: 'minmax(0, 1fr) minmax(0, 1fr)' },
    gap: 2,
  },
  eyebrow: { color: '#159d95', fontSize: 11, fontWeight: 900, letterSpacing: 1.4 },
  listStack: { mt: 1.5 },
  auditStack: { mt: 1.5, maxHeight: 360, overflow: 'auto' },
  userRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 190px 110px' },
    gap: 1,
    alignItems: 'center',
    border: '1px solid var(--app-border-soft)',
    borderRadius: '8px',
    p: 1,
  },
  userName: { color: 'var(--app-text)', fontSize: 13, fontWeight: 900 },
  mutedSmall: { color: 'var(--app-text-muted)', fontSize: 11 },
  userSelect: {
    backgroundColor: 'var(--app-surface)',
    '& fieldset': { borderColor: 'var(--app-border)', borderRadius: '8px' },
  },
  auditRow: {
    borderLeft: '4px solid #159d95',
    backgroundColor: 'var(--app-surface-soft)',
    borderRadius: '8px',
    p: 1,
  },
  auditDetails: { color: '#52677f', fontSize: 12, mt: 0.6 },
} satisfies Record<string, SxProps<Theme>>;
